### ISSUE TITLE
Rebuild documentation when building the Docker image

### ISSUE THREAD

**Issue by tristan0x** [CNS-OIST/STEPS_Docker#6]
Instead of simply copying Jupyter notebooks from `STEPS_Example` repository in the Docker image, these notebooks should be replayed with the version of STEPS built inside the image to test it. It is possible to execute a Jupyter notebook with [`nbconvert`](https://pypi.org/project/nbconvert/).

**Comment by WeiliangChenOIST** [comment]
@tristan0x who should I assign this to?

**Comment by tristan0x** [comment]
> @tristan0x who should I assign this to?

This has been done by @lkeegan
